Add Steps/Recipe/Test for Lido Staking
Railgun-Community/cookbook pull request #38
Opened 2024-12-23 15:22 UTC by Itachi546

Add steps and recipe for lido staking
1. Add step/recipe for staking ETH to get stETH and wrap it to wstETH
2. Adds step/recipe to directly stake ETH to get wstETH

2025-01-16 03:24 UTC, zy0n approved these changes

2025-01-16 13:32 UTC, mattgle requested changes
Hey! Thanks for the amount of effort put into this PR, having Lido Staking in RAILGUN sounds amazing! About the PR, I think there might be something wrong with your prettier, because the indentation is not correct, also theres OEF missing in a lot of files, make sure to check that 😄

2025-01-16 13:44 UTC, mattgle requested changes

2025-01-16 13:44 UTC, mattgle commented on src/contract/lido/lido-stETH-contract.ts
> +    }
If I'm not wrong I think you could do this change, since thse functions are still returning a promise.
```suggestion
    async balanceOf(address: string): Promise<bigint> {
        return this.contract.balanceOf(address);
    }

    async sharesOf(address: string): Promise<bigint> {
        return this.contract.sharesOf(address);
    }
```

2025-01-16 13:44 UTC, mattgle commented on src/contract/lido/lido-wstETH-contract.ts
> +        this.contract = new Contract(contractAddress, lidoWSTETHAbi, provider) as unknown as LidoWSTETH;
Is there a way to not use the `as unknown` here? Its definitely not a good practice, just asking for the context.

2025-01-16 13:44 UTC, mattgle commented on src/recipes/lido/__tests__/FORK-lido-stake-shortcut-recipe.test.ts
> +        const amountMinusFee = unshieldAmount - 25n; // Unshield Fee
extract 25n, like `const UNDSHIELD_FEE = 25n`

2025-01-16 13:44 UTC, mattgle commented on src/steps/lido/lido-wrap-steth-step.ts
> +    }
I think you can do this, can you check?
```suggestion
    private async getWrapAmount(stakeAmount: bigint): Promise<bigint> {
        const wstETHContract = new LidoWSTETHContract(this.wstETHTokenInfo.tokenAddress, this.provider);
        return await wstETHContract.getWstETHByStETH(stakeAmount);
    }
```

2025-01-16 14:10 UTC, emilbayes commented on src/contract/lido/lido-stETH-contract.ts
> +    }
`async` could even be stripped here, as there is no async logic going on anymore. The result of the functions would of course still have to be `await`ed to unwrap

2025-01-16 16:05 UTC, mattgle commented on src/contract/lido/lido-stETH-contract.ts
> +    }
Agree

2025-01-17 11:48 UTC, mattgle commented on src/contract/lido/index.ts
> +export * from './lido-wstETH-contract'
Add EOF

2025-01-17 11:49 UTC, Itachi546 commented on src/contract/lido/lido-wstETH-contract.ts
> +        this.contract = new Contract(contractAddress, lidoWSTETHAbi, provider) as unknown as LidoWSTETH;
I couldn't find any other way to replace it. It is done in same way in existing code.

2025-01-17 11:50 UTC, mattgle commented on src/recipes/lido/index.ts
> +export * from './lido-stake-shortcut-recipe';
Add EOF

2025-01-17 12:11 UTC, mattgle commented on src/steps/lido/lido-stake-shortcut-step.ts
> +    }
Does this works? I think so, can you check?
```suggestion
    private getWrappedAmount(stakeAmount: bigint): Promise<bigint> {
        const wstETHContract = new LidoWSTETHContract(
            this.wstETHTokenInfo.tokenAddress,
            this.provider,
        );
        return  wstETHContract.getWstETHByStETH(stakeAmount);
    }
```

2025-01-17 12:50 UTC, mattgle approved these changes
This is looking way better! Thanks for considering and adding all corrections and suggestions, great work! LGTM 🥇

2025-01-17 16:15 UTC, zy0n commented on src/recipes/lido/__tests__/FORK-lido-stake-shortcut-recipe.test.ts
> +        const amountMinusFee = unshieldAmount - 25n; // Unshield Fee
For what reason?

2025-01-18 14:50 UTC, linkismissing commented on src/recipes/lido/__tests__/FORK-lido-stake-recipe.test.ts
> +  it.only('[FORK] Should stake ETH to get stETH', async function () {
please remove the it.only()

2025-01-18 15:08 UTC, zy0n commented
Tests failing, due to tests running in forked repo while not having appropriate ENV values.

2025-01-18 15:08 UTC, merged

2025-06-05 21:42 UTC, zy0n commented
Don't delete this. am reverting it from the history as it is non functional as it sits.